### PR TITLE
Allow customization of item and context classes

### PR DESCRIPTION
**Pull request by thesadru**
Wake up babe new pr just dropped
```py
import miru



class MyButton(miru.Button):
    ...

class MyContext(miru.Context):
    ...

class MyView(miru.View):
    @miru.button(cls=MyButton, context_cls=MyContext, label="label")
    async def foo(self, button: MyButton, context: MyContext):
        ...
    
    @miru.button(label="label")
    async def bar(self, button: MyButton, context: MyContext):
        ...

view = MyView()
```

### CODE REVIEW

**Review by HyperGH — COMMENTED** [review]
I do not think custom context should be handled on a per-item basis, as this would just create unnecessary confusion for little benefit.

**Comment by CircuitSacul** [comment]
> I do not think custom context should be handled on a per-item basis, as this would just create unnecessary confusion for little benefit.

I kinda like it... If you make it a view-wide, then that's one less thing that users are able to customize. Imo if I want a custom context for all my buttons, I'll just write my own button decorator like this:
```py
def button(*args, **kwargs):
    return miru.button(*args, ctx_class=MyContext, **kwargs)
```

**Comment by thesadru** [comment]
This has been discussed internally, sorry for that.

While I do not think there's any chance of confusing users there are other worse problems. Especially methods like `on_timeout` which should take a uniform context type.

**Comment by CircuitSacul** [comment]
> This has been discussed internally, sorry for that.
> 
> While I do not think there's any chance of confusing users there are other worse problems. Especially methods like `on_timeout` which should take a uniform context type.

That's a good point. So then maybe do custom classes that are view-wide, and keep the custom button class.

**Comment by HyperGH** [comment]
Closing as stale, going to do own implementation.

**Pull request closed without merging**
